### ISSUE TITLE
Warning: Object value  has no method 'match'

### ISSUE THREAD

**Issue by Grawl** [Sebastian-Fitzner/grunt-data-separator#4]
It works some time ago and now I get this error:

```
Warning: Object 100%
   has no method 'match' Use --force to continue.
```

My task config:

```js
server_images:{
	options:{
		pattern:{
			matchValue:/data/,
			matchParent:true
		},
		output:'<%=yeogurt.staticServer%>/images.css'
	},
	files:{
		'<%=yeogurt.staticServer%>/style.css': '<%=yeogurt.staticServer%>/style.css'
	}
},
```

`yeogurt.staticServer` is `client/.serve`.

I tried a lot of config variances and nothing helps me. What do I wrong?

**Comment by Sebastian-Fitzner** [comment]
Can you provide a test repository? I can not reproduce the error.

**Comment by Grawl** [comment]
No, I am developing an NDA project and cannot share it.

Basically, I cannot understand why I need three paths to move some data from one file (1) to another (2). Please can you describe this?

**Comment by Grawl** [comment]
First, I looked at your [`gruntfile`](https://github.com/Sebastian-Fitzner/grunt-data-separator/blob/master/Gruntfile.js#L73) and realized that I have to provide my `style.css` twice at `files:` section. It's strange but okay.

Second, I localized a problem. **It's a parser.**

1. I generated my CSS
2. Launched `grunt-data-separator` and it fails with `Warning: Object hidden  has no method 'match'`. I realized that `hidden` there and `100%` in the title of this issue is a CSS properties.
3. I used Reformat Code function in IntelliJ IDEA.
4. Launched `grunt-data-separator` and it works.

I use `outputStyle:'compact'` in my Sass config and it does not help me. I will try to workaround the problem with some CSS prettifier but… do you think that PostCSS must parse any valid CSS? Autoprefixer and CSS-MQpacker parses my CSS properly.

**Comment by Grawl** [comment]
I tried to update `postcss` into `grunt-data-separator` but nothing changes.

**Comment by Grawl** [comment]
I tried a lot of CSS prettyfiers and nothing helps me. Only IDEA's Reformat Code helps. But I cannot embed it into my Grunt build :(

**Comment by Sebastian-Fitzner** [comment]
Okay, will take a deeper look. It would be much easier for me when you provide an example of your css lines which cause the problem.

**Comment by Grawl** [comment]
I localized a problem. It's comments nearby declarations and whitespace before closing semicolon.

Finally I do this replacements to fix my CSS to make `dataSeparator` work:

```js
			    // remove inline comments nearby declarations
			    {
				    from:/\/\*(?!\n)\s+?[\d\w\s]+?\s+?\*\/\n?/gmi,
				    to:''
			    },
			    // remove whitespace just before closing semicolon:
			    {
				    from:/(\w+:\s+[\d\w]+(\s\!\w+)?)\s;/gmi,
				    to:'$1;'
			    }
```

(I used `grunt-text-replace` for this)

So here's a problem parts:

### Inline comments nearby declarations

not working:

```css
html {
  font-family: sans-serif;
  /* 1 */
  -ms-text-size-adjust: 100%;
  /* 2 */
  -webkit-text-size-adjust: 100%;
  /* 2 */ }
```

working:

```css
html {
  font-family: sans-serif;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
   }
```

### Whitespace just before closing semicolon

not working:

```css
      .selector {
        visibility: visible ;
---------------------------^ whitespace
        color: #762a84; }
```

working:

```css
      .selector {
        visibility: visible;
---------------------------^ no whitespace
        color: #762a84; }
```

So I created a workaround but you have to fix this :wink:
